language: node_js
node_js:
  - '14'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - npm install -g codecov
  - yarn
after_success:
  - yarn lerna boostrap
  - yarn test:cover --maxWorkers=$(nproc)
  - bash <(curl -s https://codecov.io/bash)
